<?php

/**
* Implement hook_menu().
*/

function send_message_menu()
{
    $items = array();
        $items['admin/config/system/send_massage'] = array(
        'title' => t('Email templates'),
        'description' => 'Отправка email',
        'page callback' => 'send_message_settings_page',
        'access arguments' => array('administer users'),
        'type' => MENU_NORMAL_ITEM,
        );

    return $items;
}

function send_message_settings_page()
{
    if (isset($_GET['type']) && in_array($_GET['type'], array('question', 'answer'))) {
        $form = drupal_get_form('send_message_form');
        return drupal_render($form);
    } else {
        $links = l(
            'Сообщение при создании вопроса',
            url('admin/config/system/send_massage', array('absolute' => true)),
            array(
                'query' => array(
                    'type' => 'question'
                )
            )
        );
        $links .= '<br>';
        $links .= l(
            'Сообщение при создании ответа',
            url('admin/config/system/send_massage', array('absolute' => true)),
            array(
                'query' => array(
                    'type' => 'answer'
                )
            )
        );

        return $links;
    }
}

/**
 * Implement hook_form().
 */
function send_message_form($form, &$form_state)
{
    $form['send_message_e-mail_subject'] = array(
        '#type' => 'textfield',
        '#title' => t('Email subject'),
        '#description' => t('The subject of the e-mail which will be sent to users.'),
        '#size' => 40,
        '#maxlength' => 120,
        '#required' => TRUE,
    );

    $form['send_message_e-mail_text'] = array(
        '#type' => 'textarea',
        '#rows' => 10,
        '#columns' => 40,
        '#title' => t('Email text'),
        '#required' => TRUE,
        '#description'=> t('The text of the email which will be sent to users.'),
    );

    $form['send_message_e-mail_type'] = array(
        '#type' => 'hidden',
        '#value' => $_GET['type']
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Save settings'),
    );

    if (isset($_GET['type']) && in_array($_GET['type'], array('question', 'answer'))) {
        $result = db_query(
            'SELECT * FROM {email_templates} t WHERE t.type = :type',
            array(':type' => $_GET['type'])
        )->fetchObject();

        if (!empty($result)) {
            $form['send_message_e-mail_subject']['#default_value'] = $result->subject;
            $form['send_message_e-mail_text']['#default_value'] = $result->message;
            $form['send_message_e-mail_type']['#default_value'] = $result->type;
        }
    }

    return $form;
}

function send_message_form_submit($form, &$form_state)
{
    if (isset($_GET['type']) && in_array($_GET['type'], array('question', 'answer'))) {
        $query = db_query(
            'SELECT * FROM {email_templates} t WHERE t.type = :type',
            array(':type' => $_GET['type'])
        )->fetchObject();

        if (empty($query)) {
            db_insert('email_templates')
                ->fields(array(
                    'type' => $form_state['values']['send_message_e-mail_type'],
                    'subject' => $form_state['values']['send_message_e-mail_subject'],
                    'message'   => $form_state['values']['send_message_e-mail_text'],
                ))
                ->execute();

            drupal_set_message(t('Data has been successfully sent.'));
        } else {
            db_update('email_templates')
                ->fields(array(
                    'type' => $form_state['values']['send_message_e-mail_type'],
                    'subject' => $form_state['values']['send_message_e-mail_subject'],
                    'message'   => $form_state['values']['send_message_e-mail_text'],
                ))
                ->condition('type', $_GET['type'], '=')
                ->execute();

            drupal_set_message(t('Data has been update.'));
        }
    }
}